// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReceiverService.proto

package com.receive;

public final class ReceiverService {
  private ReceiverService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReceiveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReceiveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReceiveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReceiveResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ReceiverService.proto\"d\n\016ReceiveReques" +
      "t\022\025\n\rtransactionId\030\001 \001(\t\022\021\n\taccountId\030\002 " +
      "\001(\t\022\022\n\ntransferId\030\003 \001(\t\022\024\n\014creditAmount\030" +
      "\004 \001(\003\"!\n\017ReceiveResponse\022\016\n\006result\030\001 \001(\t" +
      "2=\n\016ReceiveService\022+\n\006credit\022\017.ReceiveRe" +
      "quest\032\020.ReceiveResponseB\017\n\013com.receiveP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ReceiveRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReceiveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReceiveRequest_descriptor,
        new java.lang.String[] { "TransactionId", "AccountId", "TransferId", "CreditAmount", });
    internal_static_ReceiveResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReceiveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReceiveResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
