apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ quote .Values.name }}
spec:
  hosts:
  - "*"
  gateways:
  - microservice-gateway
  http:
  - match:
    - uri:
        prefix: /{{ .Values.name }}
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: {{ .Values.port }}
        host: {{ .Values.name }}.default.svc.cluster.local