apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ quote .Values.name }}
  name: {{ quote .Values.name }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
    name: http    
  selector:
    app: {{ quote .Values.name }}
  type: NodePort
status:
  loadBalancer: {}