// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenderService.proto

package com.sender;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string input = 1;</code>
   * @return The input.
   */
  java.lang.String getInput();
  /**
   * <code>string input = 1;</code>
   * @return The bytes for input.
   */
  com.google.protobuf.ByteString
      getInputBytes();
}
