// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SenderService.proto

package com.sender;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string output = 1;</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 1;</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();
}
