server:
  port: 9000
  servlet.context-path: /order
  undertow.max-http-post-size: 0
grpc:
  server.port: 8000
  client:
    sender-service:
      address: 'static://localhost:8001'
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
      negotiationType: plaintext
#workflow.client.url: 127.0.0.1:7233
temporal:
  server: 127.0.0.1:7233
  isUseSsl: false
  namespace: 'temporal'
  workflowTaskTimeoutConfig: 1000 #millisec
  #default activity
  defaultActivityStartToCloseTimeout: 15 #second
  defaultActivityMaximumRetryAttempts: 50
  #default local activity
  defaultLocalActivityStartToCloseTimeout: 15 #second
  defaultLocalActivityMaximumRetryAttempts: 9999
  defaultLocalActivityRetryInterval: 10 #millisec
  #getInfo
  getInfoStartToCloseTimeout: 5 #second
  getInfoMaximumAttempts: 5
  worker:
    maxConcurrentActivityTaskPollers: 25 #default 5
    maxConcurrentWorkflowTaskPollers: 10 #default 2
    maxConcurrentActivityExecutionSize: 200 #default 200
    maxConcurrentWorkflowTaskExecutionSize: 200 #default 200
    maxConcurrentLocalActivityExecutionSize: 200 #default 200
    maxWorkerActivitiesPerSecond: 0 #default 0 means unlimited
    maxTaskQueueActivitiesPerSecond: 0 #default O means unlimited
  workerFactory:
    maxWorkflowThread Count: 600 #default 600
    workflowHostLocalPollThreadCount: 5 #default 5

spring:
  application.name: order
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent
  jpa:
    properties.hibernate.format_sql: true
    database: default
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
