// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReceiverService.proto

package com.receive;

public interface ReceiveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReceiveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transactionId = 1;</code>
   * @return The transactionId.
   */
  java.lang.String getTransactionId();
  /**
   * <code>string transactionId = 1;</code>
   * @return The bytes for transactionId.
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <code>string accountId = 2;</code>
   * @return The accountId.
   */
  java.lang.String getAccountId();
  /**
   * <code>string accountId = 2;</code>
   * @return The bytes for accountId.
   */
  com.google.protobuf.ByteString
      getAccountIdBytes();

  /**
   * <code>string transferId = 3;</code>
   * @return The transferId.
   */
  java.lang.String getTransferId();
  /**
   * <code>string transferId = 3;</code>
   * @return The bytes for transferId.
   */
  com.google.protobuf.ByteString
      getTransferIdBytes();

  /**
   * <code>int64 creditAmount = 4;</code>
   * @return The creditAmount.
   */
  long getCreditAmount();
}
