// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReceiverService.proto

package com.receive;

public interface ReceiveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReceiveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
