apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc
  template:
    metadata:
      labels:
        app: grpc
    spec:
      containers:
        - name: grpc
          image: sacom-sender:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: sender
spec:
  ports:
    - protocol: "TCP"
      port: 9001        # The port inside the cluster
      targetPort: 9001  # The port exposed by the service
  type: NodePort        # Type of service
  selector:
    app: grpc